/**
 * Events Name
 */

export const ENGINE_EVENTS = {
  GAME_STAGE_CHANGE: 'GAME_STAGE_CHANGE',
  GAME_TIME_CHANGE: 'GAME_TIME_CHANGE',
  GAME_DAY_CHANGE: 'GAME_DAY_CHANGE',
  GAME_ISWORKING_CHANGE: 'GAME_ISWORKING_CHANGE',
  GAME_ONWORK: 'GAME_ONWORK',
  GAME_OFFWORK: 'GAME_OFFWORK',
  GAME_DAY_X_TIME_Y: (day, time) => `GAME_DAY_${day}_TIME_${time}`
}

export const ACCOUNT_EVENTS = {
  ACCOUNT_BALANCE_CHANGE: 'ACCOUNT_BALANCE_CHANGE',
  ACCOUNT_ADD: 'ACCOUNT_ADD',
  ACCOUNT_BANKRUPT: 'ACCOUNT_BANKRUPT'
}

export const INVENTORY_EVENTS = {
  INVENTORY_IMPOTY: 'INVENTORY_IMPROT',
  INVENTORY_EXPORT: 'INVENTORY_EXPORT',
  INVENTORY_REGIST: 'INVENTORY_REGIST',
  INVENTORY_COUNT_STORAGE_COST: 'INVENTORY_COUNT_STORAGE_COST'
}

export const IO_EVENTS = {
  IO_IMPORT: 'IO_IMPORT',
  IO_EXPORT: 'IO_EXPORT',
  IO_COMPLETE: 'IO_COMPLETE'
}

export const BIDDING_EVENTS = {
  BIDDING_RELEASED: 'BIDDING_RELEASED',
  BIDDING_CANCELED: 'BIDDING_CANCELED',
  BIDDING_SIGNED: 'BIDDING_SIGNED',
  BIDDING_BREAKOFF: 'BIDDING_BREAKOFF',
  BIDDING_COMPLETED: 'BIDDING_COMPLETED'
}

export const MARKET_EVENTS = {
  MARKET_NEWS_PUBLISHED: 'MARKET_NEWS_PUBLISHED',
  MARKET_NEEDS_CHANGE: 'MARKET_NEEDS_CHANGE'
}

export const ROOM_EVENTS = {
  ROOM_JOIN: 'ROOM_JOIN',
  ROOM_LEAVE: 'ROOM_QUIT'
}

/**
 * Stage
 */
export const USER_LEVEL = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  PLAYER: 'PLAYER',
  GUEST: 'GUEST'
}

export const ENGINE_STAGE = {
  CONSTRUCTED: 'CONSTRUCTED',
  PREPARE: 'PREPARE',
  READY: 'READY',
  START: 'START',
  FINAL: 'FINAL',
  END: 'END'
}

export const TRANSPORTATION_STATUS = {
  DELIVERING: 'DELIVERING',
  COMPLETED: 'COMPLETED'
}

export const ACCOUNT_LEDGER_SIDE = {
  DEBIT: 'debit',
  CREDIT: 'credit'
}

export const BIDDING_ITEM_STAGE = {
  CONSTRUCTED: 'CONSTRUCTED',
  BIDDING: 'BIDDING',
  CANCELED: 'CANCELED',
  SIGNED: 'SIGNED',
  BREAKOFF: 'BREAKOFF',
  COMPLETED: 'COMPLETED'
}

export const BIDDING_CHAIN = {
  UPSTREAM: 'UPSTREAM',
  DOWNSTREAM: 'DOWNSTREAM'
}

export const INVENTORY_MODE = {
  PERIODIC: 'PERIODIC', // 定期盤點制
  PERPETUAL: 'PERPETUAL' // 永續盤存制
}
